### PR TITLE
Add new recipe for Tränenkuchen

### PR DESCRIPTION
**Pull request by GitUniSF**
### Summary

This pull request adds a new recipe for Tränenkuchen as suggested in issue #48 .

### Changes Made

- Added `Tränenkuchen.qmd` to the `recipes` directory.

### Related Issues

-  #48

### CODE REVIEW

**Review by lnnrtwttkhn — CHANGES_REQUESTED** [review]
Thanks for this PR @GitUniSF!

Please structure the recipe according to the [template](https://github.com/lnnrtwttkhn/recipes/blob/main/recipes/template.qmd).
For more details, see the [contributing guidelines](https://github.com/lnnrtwttkhn/recipes/blob/main/CONTRIBUTING.md). Thank you!

In addition:

- [ ] Please translate to English
- [ ] Please add your `author` information to the YAML header.

Thank you!

**Comment by GitUniSF** [comment]
Update and rename Tränenkuchen.qmd to Cheesecake with Meringue Topping.qmd

Translated the title and recipe into English.
Added author information to the YAML header.
as sugesstes in issue #60

**Comment by lnnrtwttkhn** [comment]
Hi @GitUniSF, thanks for the additional changes. One final thing:

Could you please move the file to the `/recipes` subfolder and rename to `cheesecake-with-meringue-topping.qmd`.

You can do this from the command line, executed from the root of the directory, like this:

```bash
mv "Cheesecake with Meringue Topping.qmd" cheesecake-with-meringue-topping.qmd
```

Thanks!

**Comment by lnnrtwttkhn** [comment]
Thank you @GitUniSF for the final changes. Ready to merge now! 🚀

**Comment by lnnrtwttkhn** [comment]
@allcontributors please add @GitUniSF  for bug, content, code

**Pull request merged**
